version: "3.1"
services:
  nginx-viloveul:
    image: nginx:alpine
    container_name: viloveul-nginx-dev
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "19910:80"
    depends_on:
      - php-viloveul

  php-viloveul:
    build: .
    container_name: viloveul-php-dev
    restart: always
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql-viloveul
      - redis-viloveul

  mysql-viloveul:
    image: mysql:5.7
    container_name: viloveul-mysql-dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=viloveul
      - MYSQL_DATABASE=viloveul_app
      - MYSQL_USER=viloveul
      - MYSQL_PASSWORD=viloveul
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306

  redis-viloveul:
    image: redis:alpine
    container_name: viloveul-redis-dev
