#!/usr/bin/env php
<?php

use Viloveul\Kernel\Contracts\Database;
use Viloveul\Router\Contracts\Collection;
use App\Entity\Role;
use App\Entity\RoleChild;
use App\Entity\UserRole;
use App\Entity\User;

$app = require __DIR__ . '/bootstrap.php';

$app->prepare(function (Database $db, Collection $routes) {
	$db->load();
	$user = User::updateOrCreate(
		['username' => 'admin', 'email' => 'me@viloveul.com'],
		['password' => password_hash('b1sm1llah', PASSWORD_DEFAULT), 'status' => 1]
	);
	$role = Role::updateOrCreate(
		['name' => 'admin', 'type' => 'group'],
		['type' => 'group']
	);
	$userRole = UserRole::updateOrCreate(
		['user_id' => $user->id, 'role_id' => $role->id],
		['created_at' => date('Y-m-d H:i:s')]
	);
	foreach ($routes->all() as $key => $value) {
		$access = Role::updateOrCreate(
			['name' => $key],
			['type' => 'access']
		);
		RoleChild::updateOrCreate(
			['role_id' => $role->id, 'child_id' => $access->id],
			['created_at' => date('Y-m-d H:i:s')]
		);
	}
});
